---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  # All tests specified in the `/plans/` subdir
  - job: tests
    trigger: pull_request
      #notifications:
      #failure_comment:
      #  message: "validate test failed."
    targets: &pr_test_targets
      - fedora-latest-stable
    skip_build: true
    identifier: windows_validate
    tmt_plan: "/plans/validate"
